import { Prompt } from './types';

interface PromptPack {
  title: string;
  shortTitle: string;
  emoji: string;
  description: string;
  prompts: string[];
}

export const PROMPT_PACKS: PromptPack[] = [
  {
    title: 'Loneliness Pack',
    shortTitle: 'Loneliness',
    emoji: '🌙',
    description: 'Find presence in solitude',
    prompts: [
      'When do you feel most alone, even when surrounded by people?',
      'What’s something you miss that you can’t quite name?',
      'What helps you feel connected again when the loneliness grows heavy?',
      'A time you realised someone actually understood you — what did that feel like?',
      'What does your loneliness want you to know?',
      'What’s one small thing that made you feel less alone recently?',
      'How do you show up for yourself when no one else is around?',
      'Who or what reminds you that you still belong to the world?',
      'What are you still healing from that others do not see?',
      'Something that hurt you but you didn’t let yourself feel.',
      'What do you still need to process?',
      'A moment you realised solitude didn’t have to mean loneliness.',
      'A promise to yourself to be softer here.',
      'What question are you trying to answer most in your life right now?',
      'A memory that reminded you you were never truly alone.',
      'What does belonging to yourself feel like?',
      'Something or someone that helps you feel human again.',
      'A thought that brings you comfort when you feel disconnected.',
      'What has loneliness taught you about love?',
      'What would you tell someone feeling the way you do right now?',
    ],
  },
  {
    title: 'Acceptance Pack',
    shortTitle: 'Acceptance',
    emoji: '🌿',
    description: 'Let things be as they are',
    prompts: [
      'What are you tired of fighting within yourself?',
      'What would it mean to fully accept this season of your life?',
      'When did you last forgive yourself for something small?',
      'What truth have you been resisting that’s asking to be seen?',
      'What if nothing had to change for you to feel at ease right now?',
      'What does “enough” feel like in your body?',
      'What lesson keeps returning until you finally accept it?',
      'A time when surrender turned out softer than you expected.',
      'What does letting go actually feel like?',
      'A belief you’re ready to release.',
      'A promise to myself.',
      'A thank-you note — to life, to growth, or to yourself.',
      'Something you’ve learnt to stop apologising for.',
      'What truth are you finally ready to say aloud?',
      'What’s one thing you can accept today, as it is?',
    ],
  },
  {
    title: 'Gratitude Pack',
    shortTitle: 'Gratitude',
    emoji: '🌼',
    description: 'Remembering what holds you',
    prompts: [
      'Who has shown you kindness lately, even in a small way?',
      'What’s something ordinary that quietly makes your life better?',
      'A moment from this week you’d like to hold onto a little longer.',
      'What part of yourself deserves your gratitude today?',
      'What’s something you once took for granted that you now cherish?',
      'Who do you want to thank, even if you can’t tell them directly?',
      'What does gratitude feel like when you slow down to notice it?',
      'How does your life remind you that you are supported?',
      'A thank-you note.',
      'Something small that made you smile today.',
      'Who makes your life brighter without trying?',
      'What memory reminds you that you’re cared for?',
      'How do you express appreciation when words fall short?',
      'What are you grateful for in this exact moment?',
      'What has gratitude changed in you?',
    ],
  },
  {
    title: 'Loss & Mortality Pack',
    shortTitle: 'Loss',
    emoji: '🕯️',
    description: 'Making peace with endings',
    prompts: [
      'Who or what have you had to say goodbye to recently?',
      'What part of grief still lives quietly in you?',
      'What did loving them teach you about yourself?',
      'How do you honour what you’ve lost while still moving forward?',
      'What would you say if you could have one more conversation?',
      'What endings shaped who you are today?',
      'How do you make peace with things that cannot return?',
      'What do you think remains of us after we’re gone?',
      'A memory that still carries light.',
      'A name you still speak softly in your mind.',
      'A question you never got to ask.',
      'How do you remember without holding on too tightly?',
      'What has loss taught you about love?',
      'How has grief softened or strengthened you?',
      'Who do you carry with you wherever you go?',
    ],
  },
  {
    title: 'Belonging Pack',
    shortTitle: 'Belonging',
    emoji: '🏡',
    description: 'Finding your place again',
    prompts: [
      'Where do you feel most like yourself?',
      'When was the last time you truly felt you belonged?',
      'What makes a space feel safe for you?',
      'Who sees you as you really are?',
      'What does community mean to you now?',
      'How do you know when you’ve outgrown a place or group?',
      'What parts of you are still looking for home?',
      'What helps you reconnect to your sense of belonging?',
      'Who makes you feel seen without needing to explain yourself?',
      'What part of belonging still feels out of reach?',
      'A time you created home wherever you were.',
      'What do you need from the spaces you enter?',
      'A moment you realised you didn’t have to fit in.',
      'What helps you belong to yourself first?',
      'Who reminds you that you already belong?',
    ],
  },
  {
    title: 'Self-Discovery Pack',
    shortTitle: 'Discovery',
    emoji: '🌱',
    description: 'Learning who you are beneath the noise',
    prompts: [
      'A secret you keep with yourself.',
      'I am …',
      'A truth you’ve been avoiding.',
      'When was the last time you felt completely safe?',
      'The moment you realised you were different.',
      'What part of yourself are you still learning to understand?',
      'Something you’re proud of but rarely talk about.',
      'What are you most afraid to admit you want?',
      'What question are you trying to answer most in your life right now?',
      'What are you learning about who you are when no one’s watching?',
      'What makes you feel most alive?',
      'What belief about yourself is changing?',
      'What would your younger self be proud of now?',
      'A part of you that’s growing quietly.',
      'A question that felt like a hug.',
    ],
  },
  {
    title: 'Love & Relationships Pack',
    shortTitle: 'Love',
    emoji: '💞',
    description: 'Exploring vulnerability and connection',
    prompts: [
      'The last time you felt jealous and why.',
      'What does love feel like to you when it’s safe?',
      'A memory that still makes your chest ache.',
      'What have relationships taught you about yourself?',
      'When was the last time you said “I love you” and meant it?',
      'What scares you most about being loved?',
      'Something you wish someone told you about heartbreak.',
      'Something you still miss but don’t talk about.',
      'Something you would like to hear them say.',
      'What version of love are you learning to accept now?',
      'Who makes you feel safe to love again?',
      'Who is your greatest love and why did you fall in love with him/her?',
      'What did your last relationship teach you about yourself?',
      'What does love mean to you today?',
      'What makes love worth the risk?',
    ],
  },
  {
    title: 'Growth & Transformation Pack',
    shortTitle: 'Growth',
    emoji: '🌻',
    description: 'Becoming who you’re meant to be',
    prompts: [
      'Admit something to yourself for the first time here.',
      'Something you pretend doesn’t bother you.',
      'When was the last time you surprised yourself?',
      'Something you’re still waiting for.',
      'What does starting over mean to you?',
      'What lesson keeps finding its way back to you?',
      'Something you’ve outgrown but still miss.',
      'Who are you becoming right now?',
      'A moment you realised you’d changed.',
      'What version of yourself are you leaving behind?',
      'What does growth feel like — painful, freeing, or both?',
      'How do you know when it’s time to begin again?',
      'A season that shaped you deeply.',
      'What truth did transformation demand from you?',
      'What’s something you’re finally ready to outgrow?',
    ],
  },
  {
    title: 'Manifestation Pack',
    shortTitle: 'Manifest',
    emoji: '🌙',
    description: 'Align with your desired reality',
    prompts: [
      'What would change if you truly believed you were ready?',
      'A dream that’s been waiting for you to notice it.',
      'What belief about yourself no longer fits the person you’re becoming?',
      'When do you feel most in alignment with what you want?',
      'A fear you’ve mistaken for intuition.',
      'What does “trusting the process” mean to you right now?',
      'A promise to your future self.',
      'How do you know when something is meant for you?',
      'What are you manifesting from love, not lack?',
      'A moment you realised your thoughts were creating your reality.',
      'What are you willing to release to receive what you’ve asked for?',
      'A version of you that already lives the life you’re imagining.',
      'What would happen if you stopped trying to control the outcome?',
      'A vision that feels both frightening and right.',
      'What does abundance feel like in your body?',
    ],
  },
  {
    title: 'Comparison Pack',
    shortTitle: 'Comparison',
    emoji: '🪞',
    description: 'Return to your own pace',
    prompts: [
      'A story you tell yourself when you feel behind.',
      'Who would you be if you stopped needing to prove your worth?',
      'What helps you return to your own pace?',
      'A reminder that no one’s timeline is the same.',
      'What part of you still seeks validation?',
      'When do you forget that you’re already enough?',
      'A truth that keeps you grounded in your own lane.',
      'What’s something you admire in others that you also hold within?',
      'A comparison that taught you compassion.',
      'When was the last time you celebrated your own growth?',
      'What would “enough” look like for you if no one else was watching?',
      'A moment you realised your journey doesn’t need to look like theirs.',
      'What would your life feel like if you trusted your timing completely?',
      'A version of success that finally feels like peace.',
      'What does self-trust mean to you today?',
    ],
  },
  {
    title: 'Break-up & Heartbreak Pack',
    shortTitle: 'Heartbreak',
    emoji: '💔',
    description: 'Healing from a goodbye',
    prompts: [
      'A goodbye you never really said.',
      'What did love teach you about yourself this time?',
      'Something you still miss, but not enough to return to.',
      'What boundary was born from heartbreak?',
      'A song that still carries a memory you haven’t let go of.',
      'What version of you did that love awaken?',
      'A truth you avoided during the ending.',
      'What does healing look like for you right now?',
      'A message you wrote but never sent.',
      'A part of you that still softens when you think of them.',
      'What’s something beautiful you learnt through pain?',
      'A memory that hurts less now.',
      'What are you learning to forgive yourself for?',
      'A moment that showed you you were moving on.',
      'What does closure look like when you don’t get answers?',
    ],
  },
  {
    title: 'Parenthood Pack',
    shortTitle: 'Parenthood',
    emoji: '🫶',
    description: 'Reflections on the journey of raising others',
    prompts: [
      'A lesson your child taught you without words.',
      'How has parenthood changed your definition of love?',
      'A promise you keep silently, every day.',
      'What helps you forgive yourself on hard days?',
      'A part of your childhood you’re rewriting for them.',
      'A moment you saw yourself in your child.',
      'What would you like your child to remember about you most?',
      'A truth you’re learning as they grow.',
      'What has parenthood taught you about patience?',
      'A small moment that reminded you it’s all worth it.',
    ],
  },
  {
    title: 'Childhood Trauma Pack',
    shortTitle: 'Inner Child',
    emoji: '🧸',
    description: 'Gently revisit and reparent',
    prompts: [
      'A memory your body still remembers.',
      'What did you need as a child that you didn’t receive?',
      'A part of you that’s still learning what safety feels like.',
      'What do you wish your parents had said to you more often?',
      'A rule that once protected you but now keeps you small.',
      'What are you re-teaching yourself about love?',
      'A moment you realised you could choose differently.',
      'What does reparenting yourself look like today?',
      'A word your inner child still longs to hear.',
      'What part of your childhood shaped you?',
    ],
  },
  {
    title: 'Hope Pack',
    shortTitle: 'Hope',
    emoji: '☀️',
    description: 'Finding light in the quiet moments',
    prompts: [
      'A light that found you when you weren’t looking.',
      'A reason you stayed when you almost gave up.',
      'Something that quietly gives you strength.',
      'A person who reminded you that life goes on.',
      'A moment you realised things do get better.',
      'What keeps your faith alive when you can’t see the way?',
      'A small miracle you witnessed recently.',
      'A truth that keeps you holding on.',
      'What would it mean to believe that better days are coming?',
      'A time you surprised yourself by healing.',
    ],
  },
  {
    title: 'Failure Pack',
    shortTitle: 'Failure',
    emoji: '🌒',
    description: 'Recognizing redirection and growth',
    prompts: [
      'A time failure was actually redirection.',
      'Something that didn’t work out but made you stronger.',
      'A risk you took that didn’t go as planned — and what it taught you.',
      'What failure taught you about grace.',
      'What do you need to forgive yourself for when you think about past failures?',
      'A failure you can now see as a turning point.',
      'Something you once labelled as failure, but now recognise as growth.',
      'A moment you learnt that not everything needs to be perfect to have value.',
      'What story are you ready to rewrite about your mistakes?',
      'A reminder that progress doesn’t always look like winning.',
    ],
  },
  {
    title: 'Forgiveness Pack',
    shortTitle: 'Forgiveness',
    emoji: '🌿',
    description: 'Releasing what no longer serves you',
    prompts: [
      'A person you’re still learning to forgive.',
      'What would forgiveness look like if it didn’t mean forgetting?',
      'A version of you that deserves forgiveness most.',
      'What’s something you need to forgive yourself for saying — or not saying?',
      'A moment you realised forgiveness is freedom, not permission.',
      'A pain you no longer need to hold onto.',
      'What does closure feel like to you?',
      'A part of you that’s finally ready to release the past.',
      'What does it mean to move forward without bitterness?',
      'A reminder that forgiveness begins with you.',
    ],
  },
  {
    title: 'Letters To Pack',
    shortTitle: 'Letters To',
    emoji: '💌',
    description: 'Words left unsaid',
    prompts: [
      'Dear Dad',
      'Dear Mum',
      'Dear Ex',
      'Dear Situationship',
      'Dear Younger Me',
      'Dear Future Me',
      'Dear Past Me',
      'Dear Friend I Grew Apart From',
      'Dear Person I Never Dated',
      'Dear Life',
    ],
  },
  {
    title: 'Things You Found Beautiful Pack',
    shortTitle: 'Beauty',
    emoji: '🌸',
    description: 'Noticing the gentle, small wonders',
    prompts: [
      'Your current favourite song — and why it moves you.',
      'A stranger’s kindness that stayed with you.',
      'Someone’s laugh you still remember.',
      'The best piece of advice you’ve ever received.',
      'The way you caught yourself smiling for no reason.',
      'A scent that reminded you of home.',
      'A conversation that softened you.',
      'A moment that made you stop and breathe.',
      'A memory that you still remember.',
      'A book, film, or quote that stayed with you.',
      'A small thing that reminded you of hope.',
      'A moment you realised the world is still beautiful, after all.',
    ],
  },
];


// Flatten all prompts into a single array for "Today's Prompt" logic
const allPromptsRaw: { text: string; category: string }[] = PROMPT_PACKS.flatMap(pack =>
  pack.prompts.map(promptText => ({ text: promptText, category: pack.title }))
);

export const ALL_PROMPTS: Prompt[] = allPromptsRaw.map((p, index) => ({
  id: `p-all-${index}`,
  text: p.text,
  category: p.category,
}));
